/**
 * Central Type Exports
 * Single entry point for all application types
 */

// Common types (primary source for domain entities)
export type {
  Application,
  JobListing,
  Organization,
  User,
  Recruiter,
  Platform,
  MetaSpendData,
  DailySpend,
  ChartData,
  PlatformData,
  ChatMessage,
  ChatSession,
  OrganizationFeature,
  AuditLog,
  FilterState,
  DashboardMetrics,
  ApplicationCardProps,
  JobCardProps,
  MetricsCardProps as CommonMetricsCardProps,
  LoginFormData,
  SignUpFormData,
  OrganizationFormData,
  LoadingState,
  ErrorState,
  SortDirection,
  SortConfig,
  ActionMenuItem
} from './common.types';

// Re-export ApiResponse and PaginatedResponse from common.types as the primary
export type { ApiResponse, PaginatedResponse } from './common.types';

// API types (for API client operations)
export type {
  ApiRequestConfig,
  PaginatedRequest,
  BulkOperationRequest,
  UserCreateRequest,
  UserUpdateRequest,
  UserResponse,
  UserPreferences,
  JobCreateRequest,
  JobUpdateRequest,
  JobResponse,
  JobSearchRequest,
  ApplicationCreateRequest,
  ApplicationUpdateRequest,
  ApplicationResponse,
  OrganizationCreateRequest,
  OrganizationSettings,
  OrganizationResponse,
  AnalyticsRequest,
  AnalyticsResponse,
  FileUploadRequest,
  FileUploadResponse,
  WebhookCreateRequest,
  AuditLogResponse,
  TypedApiClient,
  ApplicationStatus as APIApplicationStatus,
  BulkActionProgress,
  BulkActionRequest,
  BulkActionResult,
  ExportFormat,
  ExportOptions,
  ExportResult
} from './api.types';

// Error types
export type {
  ErrorLevel,
  ErrorBoundaryState,
  ErrorBoundaryProps,
  ErrorFallbackProps,
  ErrorContext,
  ValidationError,
  ApiError,
  NetworkError,
  ErrorServiceConfig,
  ErrorReportPayload
} from './error.types';

// Edge function types
export type {
  EdgeFunctionResponse,
  EdgeFunctionError,
  AIChatRequest,
  AIChatResponse,
  ApplicationData,
  ApplicationSubmitRequest,
  ApplicationSubmitResponse,
  TenstreetSyncRequest,
  TenstreetSyncResponse,
  TenstreetExplorerRequest,
  TenstreetExplorerResponse,
  WebhookPayload,
  WebhookResponse,
  ClientWebhookRequest,
  ClientWebhookResponse,
  MetaLeadsRequest,
  MetaLeadData,
  MetaLeadsResponse,
  MetaAnalyticsRequest,
  MetaAnalyticsResponse,
  ElevenLabsVoice,
  ElevenLabsRequest,
  ElevenLabsResponse,
  AnalyticsQueryRequest,
  AnalyticsQueryResponse,
  ExportRequest,
  ExportResponse,
  RateLimitInfo,
  RateLimitedResponse,
  ScreeningRequest,
  ScreeningResponse,
  SMSRequest,
  SMSResponse,
  DocumentUploadRequest,
  DocumentUploadResponse,
  EdgeFunctionName,
  EdgeFunctionInvokeOptions
} from './edge-function.types';

// Service types
export type {
  ServiceResponse,
  PaginatedServiceResponse,
  BaseFilters,
  DateRangeFilter,
  StatusFilter,
  OrganizationFilter,
  ApplicationFilters,
  ApplicationServiceData,
  JobFilters,
  JobServiceData,
  AnalyticsFilters,
  ApplicationAnalytics,
  SpendAnalytics,
  UserFilters,
  UserServiceData,
  OrganizationFilters,
  OrganizationServiceData,
  TenstreetApplicantData,
  TenstreetXchangeData,
  TenstreetSyncStatus,
  WebhookServiceData,
  WebhookLogEntry,
  CacheEntry,
  CacheConfig,
  ServiceError,
  ErrorLogEntry,
  MetricCardData,
  ChartDataPoint,
  TimeSeriesData,
  ExportConfig,
  ImportConfig,
  ImportResult,
  BulkOperationConfig,
  BulkOperationProgress,
  BulkOperationResult
} from './service.types';

// Component types
export type {
  BaseComponentProps,
  InteractiveComponentProps,
  IconComponent,
  IconProps,
  FormFieldProps,
  SelectOption,
  FilterChangeHandler,
  TableColumn,
  TableRowAction,
  TableProps,
  DialogProps,
  ConfirmDialogProps,
  MetricCardProps,
  ActionCardProps,
  NavItem,
  BreadcrumbItem,
  FilterConfig,
  FilterPanelProps,
  ListItem,
  ListProps,
  ChartConfig,
  ChartProps,
  SkeletonProps,
  ToastData,
  PaginationProps,
  SearchProps,
  StatusVariant,
  StatusBadgeProps,
  AvatarProps,
  EmptyStateProps,
  ErrorDisplayProps
} from './component.types';

// Tenstreet types from central index
export * from './tenstreet';
