-- Clear existing job listings data
DELETE FROM applications;
DELETE FROM daily_spend;
DELETE FROM job_listings;

-- Insert 39 realistic job listings with descriptions
INSERT INTO job_listings (
  user_id, platform_id, category_id, client_id, title, description, job_description, 
  location, city, state, dest_city, dest_state, salary_min, salary_max, salary_type, 
  budget, status, experience_level, remote_type, client, job_id, url
) VALUES 
-- Get platform and category IDs from existing tables
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Senior Software Engineer',
  'Full-time software engineering position',
  'We are seeking a Senior Software Engineer to join our dynamic team. You will be responsible for designing, developing, and maintaining scalable web applications using modern technologies including React, Node.js, and cloud platforms. The ideal candidate has 5+ years of experience in full-stack development.',
  'San Francisco, CA',
  'San Francisco',
  'CA',
  NULL,
  NULL,
  120000,
  180000,
  'yearly',
  5000,
  'active',
  'senior',
  'hybrid',
  'TechCorp Solutions',
  'TC-2024-001',
  'https://techcorp.com/jobs/senior-engineer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Marketing Manager',
  'Digital marketing leadership role',
  'Join our marketing team as a Marketing Manager where you will lead digital campaigns, manage social media strategy, and drive brand awareness. You will work with cross-functional teams to develop and execute marketing strategies that drive customer acquisition and retention.',
  'New York, NY',
  'New York',
  'NY',
  NULL,
  NULL,
  75000,
  95000,
  'yearly',
  3000,
  'active',
  'mid',
  'on-site',
  'BrandForce Inc',
  'BF-2024-002',
  'https://brandforce.com/careers/marketing-manager'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Data Scientist',
  'Advanced analytics and machine learning',
  'We are looking for a Data Scientist to extract insights from large datasets and build predictive models. You will work with Python, R, SQL, and machine learning frameworks to solve complex business problems and drive data-driven decision making.',
  'Austin, TX',
  'Austin',
  'TX',
  NULL,
  NULL,
  95000,
  140000,
  'yearly',
  4500,
  'active',
  'senior',
  'remote',
  'DataTech Analytics',
  'DT-2024-003',
  'https://datatech.com/jobs/data-scientist'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'UX/UI Designer',
  'Creative design for web and mobile',
  'Join our design team to create intuitive and beautiful user experiences. You will be responsible for user research, wireframing, prototyping, and visual design for web and mobile applications. Experience with Figma, Adobe Creative Suite, and user-centered design principles required.',
  'Los Angeles, CA',
  'Los Angeles',
  'CA',
  NULL,
  NULL,
  70000,
  100000,
  'yearly',
  3500,
  'active',
  'mid',
  'hybrid',
  'Creative Studios LLC',
  'CS-2024-004',
  'https://creativestudios.com/careers/ux-designer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Project Manager',
  'Agile project management',
  'We need an experienced Project Manager to lead cross-functional teams and deliver projects on time and within budget. You will be responsible for project planning, risk management, stakeholder communication, and ensuring quality deliverables using Agile methodologies.',
  'Chicago, IL',
  'Chicago',
  'IL',
  NULL,
  NULL,
  80000,
  110000,
  'yearly',
  2800,
  'active',
  'senior',
  'on-site',
  'Agile Solutions Corp',
  'AS-2024-005',
  'https://agilesolutions.com/jobs/project-manager'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'DevOps Engineer',
  'Cloud infrastructure and automation',
  'Join our DevOps team to build and maintain scalable cloud infrastructure. You will work with AWS, Docker, Kubernetes, and CI/CD pipelines to ensure reliable and efficient deployment processes. Experience with Infrastructure as Code and monitoring tools preferred.',
  'Seattle, WA',
  'Seattle',
  'WA',
  NULL,
  NULL,
  105000,
  150000,
  'yearly',
  4000,
  'active',
  'senior',
  'remote',
  'CloudTech Systems',
  'CT-2024-006',
  'https://cloudtech.com/careers/devops-engineer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Sales Representative',
  'B2B software sales',
  'We are seeking a motivated Sales Representative to drive revenue growth through new client acquisition and account management. You will be responsible for lead generation, product demonstrations, contract negotiations, and maintaining strong customer relationships.',
  'Miami, FL',
  'Miami',
  'FL',
  NULL,
  NULL,
  50000,
  80000,
  'yearly',
  2500,
  'active',
  'entry',
  'hybrid',
  'SalesPro Inc',
  'SP-2024-007',
  'https://salespro.com/jobs/sales-rep'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Full Stack Developer',
  'React and Node.js development',
  'Looking for a Full Stack Developer to build modern web applications using React, Node.js, and MongoDB. You will work on both frontend and backend development, API design, database optimization, and ensuring responsive design across all devices.',
  'Denver, CO',
  'Denver',
  'CO',
  NULL,
  NULL,
  85000,
  120000,
  'yearly',
  3800,
  'active',
  'mid',
  'remote',
  'WebDev Solutions',
  'WD-2024-008',
  'https://webdevsolutions.com/careers/fullstack'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Product Manager',
  'Product strategy and roadmap',
  'We need a Product Manager to define product strategy, manage roadmaps, and work with engineering and design teams to deliver exceptional products. You will conduct market research, analyze user feedback, and drive product decisions based on data and customer needs.',
  'Boston, MA',
  'Boston',
  'MA',
  NULL,
  NULL,
  100000,
  140000,
  'yearly',
  4200,
  'active',
  'senior',
  'hybrid',
  'ProductTech Inc',
  'PT-2024-009',
  'https://producttech.com/jobs/product-manager'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Quality Assurance Engineer',
  'Software testing and automation',
  'Join our QA team to ensure the highest quality of our software products. You will design and execute test plans, develop automated test scripts, perform regression testing, and work closely with development teams to identify and resolve issues.',
  'Phoenix, AZ',
  'Phoenix',
  'AZ',
  NULL,
  NULL,
  65000,
  90000,
  'yearly',
  2200,
  'active',
  'mid',
  'on-site',
  'QualityFirst Labs',
  'QF-2024-010',
  'https://qualityfirst.com/careers/qa-engineer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Business Analyst',
  'Process improvement and analysis',
  'We are seeking a Business Analyst to analyze business processes, identify improvement opportunities, and work with stakeholders to implement solutions. You will gather requirements, create documentation, and facilitate communication between business and technical teams.',
  'Atlanta, GA',
  'Atlanta',
  'GA',
  NULL,
  NULL,
  70000,
  95000,
  'yearly',
  2800,
  'active',
  'mid',
  'hybrid',
  'Analytics Pro Corp',
  'AP-2024-011',
  'https://analyticspro.com/jobs/business-analyst'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Cybersecurity Specialist',
  'Information security and compliance',
  'Join our security team to protect our organization from cyber threats. You will monitor security systems, conduct vulnerability assessments, implement security policies, and respond to security incidents. Experience with security frameworks and compliance standards required.',
  'Washington, DC',
  'Washington',
  'DC',
  NULL,
  NULL,
  90000,
  130000,
  'yearly',
  3600,
  'active',
  'senior',
  'on-site',
  'SecureTech Solutions',
  'ST-2024-012',
  'https://securetech.com/careers/cybersecurity'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Mobile App Developer',
  'iOS and Android development',
  'We need a Mobile App Developer to create innovative mobile applications for iOS and Android platforms. You will work with React Native, Swift, and Kotlin to build user-friendly apps with seamless performance and intuitive design.',
  'Portland, OR',
  'Portland',
  'OR',
  NULL,
  NULL,
  80000,
  115000,
  'yearly',
  3400,
  'active',
  'mid',
  'remote',
  'MobileFirst Dev',
  'MF-2024-013',
  'https://mobilefirst.com/jobs/mobile-developer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Database Administrator',
  'Database management and optimization',
  'Looking for a Database Administrator to manage and optimize our database systems. You will be responsible for database design, performance tuning, backup and recovery, security implementation, and ensuring high availability of critical data systems.',
  'Dallas, TX',
  'Dallas',
  'TX',
  NULL,
  NULL,
  75000,
  105000,
  'yearly',
  3000,
  'active',
  'senior',
  'on-site',
  'DataBase Pro Inc',
  'DB-2024-014',
  'https://databasepro.com/careers/dba'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Content Marketing Specialist',
  'Content creation and strategy',
  'Join our marketing team as a Content Marketing Specialist to create engaging content across multiple channels. You will develop content strategies, write blog posts, create social media content, and manage content calendars to drive brand awareness and engagement.',
  'Nashville, TN',
  'Nashville',
  'TN',
  NULL,
  NULL,
  55000,
  75000,
  'yearly',
  2400,
  'active',
  'mid',
  'remote',
  'Content Creators LLC',
  'CC-2024-015',
  'https://contentcreators.com/jobs/content-specialist'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Network Engineer',
  'Network infrastructure and security',
  'We are seeking a Network Engineer to design, implement, and maintain our network infrastructure. You will work with routers, switches, firewalls, and wireless systems to ensure reliable and secure network connectivity across the organization.',
  'San Diego, CA',
  'San Diego',
  'CA',
  NULL,
  NULL,
  85000,
  120000,
  'yearly',
  3200,
  'active',
  'senior',
  'hybrid',
  'NetworkTech Corp',
  'NT-2024-016',
  'https://networktech.com/careers/network-engineer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'HR Generalist',
  'Human resources management',
  'Join our HR team as an HR Generalist to support all aspects of human resources including recruitment, employee relations, benefits administration, and compliance. You will work with managers and employees to ensure a positive workplace culture.',
  'Minneapolis, MN',
  'Minneapolis',
  'MN',
  NULL,
  NULL,
  60000,
  80000,
  'yearly',
  2600,
  'active',
  'mid',
  'on-site',
  'People First HR',
  'PF-2024-017',
  'https://peoplefirst.com/jobs/hr-generalist'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Financial Analyst',
  'Financial planning and analysis',
  'We need a Financial Analyst to support financial planning, budgeting, and analysis activities. You will prepare financial reports, conduct variance analysis, build financial models, and provide insights to support strategic business decisions.',
  'Charlotte, NC',
  'Charlotte',
  'NC',
  NULL,
  NULL,
  65000,
  85000,
  'yearly',
  2700,
  'active',
  'mid',
  'hybrid',
  'FinanceWorks Inc',
  'FW-2024-018',
  'https://financeworks.com/careers/financial-analyst'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Technical Writer',
  'Documentation and technical communication',
  'Looking for a Technical Writer to create clear and comprehensive documentation for our software products. You will work with engineering teams to understand complex technical concepts and translate them into user-friendly documentation and guides.',
  'Raleigh, NC',
  'Raleigh',
  'NC',
  NULL,
  NULL,
  60000,
  80000,
  'yearly',
  2500,
  'active',
  'mid',
  'remote',
  'TechDocs Solutions',
  'TD-2024-019',
  'https://techdocs.com/jobs/technical-writer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Machine Learning Engineer',
  'AI and machine learning development',
  'Join our AI team as a Machine Learning Engineer to develop and deploy machine learning models. You will work with Python, TensorFlow, PyTorch, and cloud ML platforms to build scalable AI solutions that solve real-world business problems.',
  'San Jose, CA',
  'San Jose',
  'CA',
  NULL,
  NULL,
  130000,
  180000,
  'yearly',
  5500,
  'active',
  'senior',
  'remote',
  'AI Innovations Lab',
  'AI-2024-020',
  'https://aiinnovations.com/careers/ml-engineer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Customer Success Manager',
  'Client relationship management',
  'We are seeking a Customer Success Manager to ensure our clients achieve their desired outcomes with our products. You will manage client relationships, provide onboarding support, conduct regular check-ins, and identify opportunities for account growth.',
  'Tampa, FL',
  'Tampa',
  'FL',
  NULL,
  NULL,
  70000,
  95000,
  'yearly',
  3000,
  'active',
  'mid',
  'hybrid',
  'Success Partners Inc',
  'SU-2024-021',
  'https://successpartners.com/jobs/customer-success'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Cloud Architect',
  'Enterprise cloud solutions',
  'Looking for a Cloud Architect to design and implement scalable cloud infrastructure solutions. You will work with AWS, Azure, and GCP to architect enterprise-level cloud solutions that are secure, cost-effective, and performance-optimized.',
  'Houston, TX',
  'Houston',
  'TX',
  NULL,
  NULL,
  140000,
  190000,
  'yearly',
  6000,
  'active',
  'senior',
  'remote',
  'CloudArch Solutions',
  'CA-2024-022',
  'https://cloudarch.com/careers/cloud-architect'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Frontend Developer',
  'Modern JavaScript frameworks',
  'Join our frontend team to build responsive and interactive user interfaces using React, Vue.js, and modern CSS frameworks. You will collaborate with designers and backend developers to create seamless user experiences across web and mobile platforms.',
  'Las Vegas, NV',
  'Las Vegas',
  'NV',
  NULL,
  NULL,
  75000,
  105000,
  'yearly',
  3200,
  'active',
  'mid',
  'remote',
  'Frontend Masters',
  'FM-2024-023',
  'https://frontendmasters.com/jobs/frontend-developer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Operations Manager',
  'Business operations and efficiency',
  'We need an Operations Manager to oversee daily business operations and drive operational efficiency. You will manage processes, optimize workflows, coordinate between departments, and implement systems to improve productivity and quality.',
  'Kansas City, MO',
  'Kansas City',
  'MO',
  NULL,
  NULL,
  75000,
  100000,
  'yearly',
  3100,
  'active',
  'senior',
  'on-site',
  'OpsTech Corp',
  'OT-2024-024',
  'https://opstech.com/careers/operations-manager'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Backend Developer',
  'Server-side development',
  'Looking for a Backend Developer to build robust server-side applications using Node.js, Python, or Java. You will design APIs, work with databases, implement security measures, and ensure scalable backend architecture for our applications.',
  'Philadelphia, PA',
  'Philadelphia',
  'PA',
  NULL,
  NULL,
  80000,
  115000,
  'yearly',
  3400,
  'active',
  'mid',
  'hybrid',
  'BackendPro Dev',
  'BP-2024-025',
  'https://backendpro.com/jobs/backend-developer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Digital Marketing Coordinator',
  'Multi-channel marketing campaigns',
  'Join our marketing team as a Digital Marketing Coordinator to execute digital marketing campaigns across multiple channels. You will manage social media, email marketing, PPC campaigns, and analyze campaign performance to optimize results.',
  'Orlando, FL',
  'Orlando',
  'FL',
  NULL,
  NULL,
  45000,
  65000,
  'yearly',
  2200,
  'active',
  'entry',
  'remote',
  'DigitalBoost Marketing',
  'DB-2024-026',
  'https://digitalboost.com/careers/marketing-coordinator'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Systems Administrator',
  'IT infrastructure management',
  'We are seeking a Systems Administrator to manage and maintain our IT infrastructure. You will be responsible for server administration, network management, user support, backup systems, and ensuring the security and reliability of our IT environment.',
  'Sacramento, CA',
  'Sacramento',
  'CA',
  NULL,
  NULL,
  70000,
  95000,
  'yearly',
  2900,
  'active',
  'mid',
  'on-site',
  'SysAdmin Solutions',
  'SA-2024-027',
  'https://sysadmin.com/jobs/systems-administrator'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Account Manager',
  'Client account management',
  'Looking for an Account Manager to maintain and grow relationships with existing clients. You will serve as the primary point of contact, understand client needs, coordinate service delivery, and identify opportunities for account expansion.',
  'Salt Lake City, UT',
  'Salt Lake City',
  'UT',
  NULL,
  NULL,
  60000,
  85000,
  'yearly',
  2800,
  'active',
  'mid',
  'hybrid',
  'AccountPro Management',
  'AM-2024-028',
  'https://accountpro.com/careers/account-manager'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Software Architect',
  'Enterprise software design',
  'Join our architecture team as a Software Architect to design scalable and maintainable software systems. You will define technical standards, guide development teams, make technology decisions, and ensure architectural consistency across projects.',
  'Richmond, VA',
  'Richmond',
  'VA',
  NULL,
  NULL,
  130000,
  170000,
  'yearly',
  5200,
  'active',
  'senior',
  'remote',
  'ArchTech Systems',
  'AT-2024-029',
  'https://archtech.com/jobs/software-architect'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'E-commerce Specialist',
  'Online retail management',
  'We need an E-commerce Specialist to manage our online retail operations. You will optimize product listings, manage inventory, analyze sales data, implement marketing strategies, and ensure a seamless customer shopping experience.',
  'Columbus, OH',
  'Columbus',
  'OH',
  NULL,
  NULL,
  55000,
  75000,
  'yearly',
  2600,
  'active',
  'mid',
  'remote',
  'E-Shop Solutions',
  'ES-2024-030',
  'https://eshop.com/careers/ecommerce-specialist'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Scrum Master',
  'Agile project facilitation',
  'Looking for a certified Scrum Master to facilitate Agile development processes. You will coach teams on Scrum practices, remove impediments, facilitate ceremonies, and help teams continuously improve their delivery capabilities.',
  'Indianapolis, IN',
  'Indianapolis',
  'IN',
  NULL,
  NULL,
  85000,
  110000,
  'yearly',
  3300,
  'active',
  'senior',
  'hybrid',
  'Agile Masters Inc',
  'AG-2024-031',
  'https://agilemasters.com/jobs/scrum-master'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Social Media Manager',
  'Social media strategy and content',
  'Join our marketing team as a Social Media Manager to develop and execute social media strategies across multiple platforms. You will create engaging content, manage community interactions, analyze performance metrics, and grow our social media presence.',
  'Memphis, TN',
  'Memphis',
  'TN',
  NULL,
  NULL,
  50000,
  70000,
  'yearly',
  2400,
  'active',
  'mid',
  'remote',
  'Social Boost Media',
  'SB-2024-032',
  'https://socialboost.com/careers/social-media-manager'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Research & Development Engineer',
  'Innovation and product development',
  'We are seeking an R&D Engineer to drive innovation and develop next-generation products. You will conduct research, design experiments, prototype new technologies, and collaborate with cross-functional teams to bring innovative solutions to market.',
  'Madison, WI',
  'Madison',
  'WI',
  NULL,
  NULL,
  90000,
  125000,
  'yearly',
  4000,
  'active',
  'senior',
  'on-site',
  'Innovation Labs Corp',
  'IL-2024-033',
  'https://innovationlabs.com/jobs/rd-engineer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Procurement Specialist',
  'Supply chain and vendor management',
  'Looking for a Procurement Specialist to manage supplier relationships and optimize procurement processes. You will negotiate contracts, evaluate vendors, manage purchase orders, and ensure cost-effective procurement of goods and services.',
  'Boise, ID',
  'Boise',
  'ID',
  NULL,
  NULL,
  55000,
  75000,
  'yearly',
  2500,
  'active',
  'mid',
  'hybrid',
  'ProcureTech Inc',
  'PR-2024-034',
  'https://procuretech.com/careers/procurement-specialist'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Training Specialist',
  'Employee development and education',
  'Join our HR team as a Training Specialist to design and deliver employee training programs. You will assess training needs, develop curriculum, conduct workshops, and evaluate training effectiveness to support employee development and organizational goals.',
  'Albuquerque, NM',
  'Albuquerque',
  'NM',
  NULL,
  NULL,
  50000,
  70000,
  'yearly',
  2300,
  'active',
  'mid',
  'on-site',
  'TrainPro Solutions',
  'TP-2024-035',
  'https://trainpro.com/jobs/training-specialist'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Business Development Manager',
  'Strategic partnerships and growth',
  'We are seeking a Business Development Manager to identify and pursue new business opportunities. You will build strategic partnerships, develop market expansion strategies, negotiate deals, and drive revenue growth through new client acquisition.',
  'Oklahoma City, OK',
  'Oklahoma City',
  'OK',
  NULL,
  NULL,
  75000,
  105000,
  'yearly',
  3200,
  'active',
  'senior',
  'hybrid',
  'GrowthTech Partners',
  'GT-2024-036',
  'https://growthtech.com/careers/business-development'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Compliance Officer',
  'Regulatory compliance and risk management',
  'Looking for a Compliance Officer to ensure our organization adheres to regulatory requirements and industry standards. You will develop compliance policies, conduct audits, manage risk assessments, and provide compliance training to staff.',
  'Hartford, CT',
  'Hartford',
  'CT',
  NULL,
  NULL,
  80000,
  110000,
  'yearly',
  3400,
  'active',
  'senior',
  'on-site',
  'Compliance Solutions Corp',
  'CO-2024-037',
  'https://compliancesolutions.com/jobs/compliance-officer'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Technical Support Engineer',
  'Customer technical assistance',
  'Join our support team as a Technical Support Engineer to provide technical assistance to our customers. You will troubleshoot software issues, resolve technical problems, create documentation, and work with development teams to improve product quality.',
  'Tucson, AZ',
  'Tucson',
  'AZ',
  NULL,
  NULL,
  60000,
  80000,
  'yearly',
  2600,
  'active',
  'mid',
  'remote',
  'SupportTech Solutions',
  'ST-2024-038',
  'https://supporttech.com/careers/technical-support'
),
(
  (SELECT id FROM profiles LIMIT 1),
  (SELECT id FROM platforms WHERE name = 'Meta' LIMIT 1),
  (SELECT id FROM job_categories LIMIT 1),
  (SELECT id FROM clients LIMIT 1),
  'Supply Chain Analyst',
  'Logistics and inventory optimization',
  'We need a Supply Chain Analyst to optimize our supply chain operations. You will analyze logistics data, forecast demand, manage inventory levels, identify cost savings opportunities, and work with suppliers to improve efficiency and reduce costs.',
  'Birmingham, AL',
  'Birmingham',
  'AL',
  NULL,
  NULL,
  65000,
  85000,
  'yearly',
  2800,
  'active',
  'mid',
  'hybrid',
  'SupplyChain Pro Inc',
  'SC-2024-039',
  'https://supplychain.com/jobs/supply-chain-analyst'
);