// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { logger } from '@/lib/logger';

const SUPABASE_URL = "https://auwhcdpppldjlcaxzsme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1d2hjZHBwcGxkamxjYXh6c21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDg1NjAsImV4cCI6MjA2NTMyNDU2MH0._K3Se_I9Y5dGmV-42V4MJvj4AqSWouXRTXVArOVASdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: window.localStorage,
    storageKey: 'supabase.auth.token',
    flowType: 'pkce'
  }
});

// Global auth error handler - clears stale tokens to prevent app crashes
supabase.auth.onAuthStateChange((event, session) => {
  // Log auth events for debugging
  logger.log('Auth event', { 
    event,
    hasSession: !!session,
    userId: session?.user?.id ? session.user.id.substring(0, 8) : null,
    hasAccessToken: !!session?.access_token,
    context: 'SUPABASE_CLIENT'
  });

  // Handle specific events
  switch (event) {
    case 'INITIAL_SESSION':
      logger.log('Initial session loaded', {
        isAuthenticated: !!session?.user,
        context: 'SUPABASE_CLIENT'
      });
      break;
      
    case 'TOKEN_REFRESHED':
      if (session) {
        logger.log('Token refreshed successfully', { context: 'SUPABASE_CLIENT' });
      } else {
        logger.warn('TOKEN_REFRESHED but no session - possible refresh failure', { context: 'SUPABASE_CLIENT' });
      }
      break;
      
    case 'SIGNED_IN':
      logger.log('User signed in', {
        provider: session?.user?.app_metadata?.provider || 'email',
        context: 'SUPABASE_CLIENT'
      });
      break;
      
    case 'SIGNED_OUT':
      logger.log('User signed out - clearing auth token', { context: 'SUPABASE_CLIENT' });
      try {
        localStorage.removeItem('supabase.auth.token');
        logger.log('Auth token cleared from localStorage', { context: 'SUPABASE_CLIENT' });
      } catch (e) {
        logger.error('Error clearing token', e, { context: 'SUPABASE_CLIENT' });
      }
      break;
      
    case 'USER_UPDATED':
      logger.log('User updated', { context: 'SUPABASE_CLIENT' });
      break;
      
    case 'PASSWORD_RECOVERY':
      logger.log('Password recovery initiated', { context: 'SUPABASE_CLIENT' });
      break;
      
    default:
      logger.log('Unhandled auth event', { event, context: 'SUPABASE_CLIENT' });
  }
});
